removing setup.sh (may fix PL-702?)

diff --git a/package-scripts/private-chef/postinst b/package-scripts/private-chef/postinst
--- a/package-scripts/private-chef/postinst
+++ b/package-scripts/private-chef/postinst
@@ -1,3 +1,22 @@
 #!/bin/bash
+#
+# Perform necessary private-chef setup steps after package is installed.
+#
 
-/opt/opscode/setup.sh
+PROGNAME=$(basename $0)
+
+function error_exit
+{
+	echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
+	exit 1
+}
+
+ln -sf /opt/opscode/bin/private-chef-ctl /usr/bin || error_exit "Cannot link private-chef-ctl in /usr/bin"
+  
+[ -e /etc/opscode/chef-server-running.json ] &&  /opt/opscode/bin/private-chef-ctl reconfigure
+
+
+echo "Thank you for installing Chef!"
+
+exit 0
+
