[preinst/postrm] Simplify preinst warning
After some discussion we aren't sure we want to use this method
because of the impact that it will have on automation, but if we do go
with it, we think that this simplified check is all that we needed.

Signed-off-by: Steven Danna <steve@chef.io>
Signed-off-by: Prajakta Purohit <prajakta@chef.io>

diff --git a/omnibus/package-scripts/chef-server/preinst b/omnibus/package-scripts/chef-server/preinst
--- a/omnibus/package-scripts/chef-server/preinst
+++ b/omnibus/package-scripts/chef-server/preinst
@@ -7,49 +7,46 @@ PROGNAME=$(basename $0)
 
 function error_exit
 {
-	echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
-	exit 1
+    echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
+    exit 1
 }
-
-version=$(awk '/chef-server/{ split($2,a,"+");print a[1];exit }' /opt/opscode/version-manifest.txt)
 
 confirm () {
-  read -r -p "Do you want to continue [y/n]" response
-  case "$response" in
+    read -r -p "Do you want to continue [y/n]" response
+    case "$response" in
         [yY][eE][sS]|[yY])
-            echo "Putting Chef Infra Server in maintenance mode for reindex."
+            exit 0
             ;;
         *)
-            echo "Doing nothing. You can continue using your existing Chef Infra Server."
-            exit
+            error_exit "Doing nothing. You can continue using your existing Chef Infra Server."
             ;;
-  esac
+    esac
 }
 
-first_elasticsearch_internal_install () {
-  IFS=. read -r major minor patch <<< "$version"
-  # Installing the version of Chef Infra Server with internal es.
-  # Installing 13.3 or 13.4
-  if [ $major -ge 13 -a $minor -ge 3 ]
-  then
-    #fresh install
-    if [-f /etc/opscode/chef-server-running.json]
-    then
-      if [ -d /opt/opscode/sv/opscode-solr4 && ! -d /opt/opscode/sv/elasticsearch]
-      then
-        echo "############################ NOTICE ##################################"
-        echo "This install will replace internal solr with elasticsearch for search.\n"
-        echo "There will be a full reindex of data for elasticsearch.\n"
-        echo "It can take anywhere between a few seconds to a couple of hours\n"
-        echo "for the reindex to complete.\n"
-        echo "Services will be down for the duration of the reindex.\n"
-        echo "Please take a full backup before proceeding.\n"
-        confirm
-      fi
+warn_about_search_reindex() {
+    # If this is a fresh install, we don't need to worry about the
+    # solr migration
+    if [ ! -e /etc/opscode/chef-server-running.json ]; then
+        return
     fi
-  fi
+
+    if [ -d /opt/opscode/sv/opscode-solr4 ]; then
+        echo "############################ NOTICE ##################################"
+        echo ""
+        echo "It appears that this Chef Infra Server has Solr enabled."
+        echo ""
+        echo "By default, Chef Infra Server now uses Elasticsearch. To migrate to elasticsearch"
+        echo "requires a full data reindex."
+        echo ""
+        echo "The reindex can take a long time if you have a large amount of data. Your chef server"
+        echo "will be down for the duration of the reindex."
+        echo ""
+        echo "We recommend taking a full backend before proceeding."
+        echo ""
+        echo "############################ NOTICE ##################################"
+        confirm
+    fi
 }
 
-first_elasticsearch_internal_install
-
+warn_about_search_reindex
 exit 0
